anguage: java
jdk:
- openjdk8
branches:
  only:
  - master
cache:
  directories:
    - '$HOME/.m2/repository'
before_install:
  - chmod +x mvnw


#after_success:
#  - mvn clean test jacoco:report coveralls:report
#script: "./stream/mvn clean install"